use crate::codegen::{
    kind_table,
    rust::{field_binding, string_literal},
};
use crate::project::{schema::WidgetKind, ui_tree::UiTree};
use std::collections::HashSet;
use std::fs;
use std::path::Path;

/// Write a complete compilable Rust project to `dest` folder.
pub fn write_project(tree: &UiTree, dest: &Path) -> Result<(), String> {
    let src_dir = dest.join("src");
    fs::create_dir_all(&src_dir).map_err(|e| format!("create dirs: {e}"))?;
    fs::write(dest.join("Cargo.toml"), gen_cargo_toml()).map_err(|e| format!("Cargo.toml: {e}"))?;
    fs::write(src_dir.join("main.rs"), gen_main_rs(tree)).map_err(|e| format!("main.rs: {e}"))?;
    fs::write(src_dir.join("app.rs"), gen_app_rs(tree)).map_err(|e| format!("app.rs: {e}"))?;
    Ok(())
}

// ---------------------------------------------------------------------------

fn gen_cargo_toml() -> String {
    r#"[package]
name = "exported_app"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui   = "0.29"
"#
    .to_owned()
}

fn gen_main_rs(tree: &UiTree) -> String {
    let title = string_literal(&tree.app_props.title);
    let w = tree.app_props.win_w as u32;
    let h = tree.app_props.win_h as u32;
    format!(
        r#"mod app;
use app::ExportedApp;

fn main() -> eframe::Result<()> {{
    let options = eframe::NativeOptions {{
        viewport: egui::ViewportBuilder::default()
            .with_title({title})
            .with_inner_size([{w}.0, {h}.0]),
        ..Default::default()
    }};
    eframe::run_native(
        {title},
        options,
        Box::new(|_cc| Ok(Box::new(ExportedApp::default()))),
    )
}}
"#
    )
}

// ---------------------------------------------------------------------------

struct BoundField {
    name: String,
    ty: &'static str,
    default_expr: String,
}

fn gen_app_rs(tree: &UiTree) -> String {
    let mut seen: HashSet<String> = HashSet::new();
    let mut fields: Vec<BoundField> = Vec::new();

    for w in &tree.widgets {
        // Standard state binding
        if let Some(name) = field_binding(w.state_binding.as_deref()) {
            if seen.insert(name.to_owned()) {
                if let Some(info) = kind_table::state_info(&w.kind) {
                    fields.push(BoundField {
                        name: name.to_owned(),
                        ty: info.rust_type,
                        default_expr: default_expr_for_widget(w),
                    });
                }
            }
        }
        // Bound label field
        if let Some(ref lb) = w.label_binding {
            if let Some(b) = field_binding(Some(lb.as_str())) {
                if seen.insert(b.to_owned()) {
                    fields.push(BoundField {
                        name: b.to_owned(),
                        ty: "String",
                        default_expr: "String::new()".to_owned(),
                    });
                }
            }
        }
        // Custom props
        for prop in &w.custom_props {
            if let Some(b) = field_binding(Some(prop.name.as_str())) {
                if seen.insert(b.to_owned()) {
                    fields.push(BoundField {
                        name: b.to_owned(),
                        ty: prop.ty.rust_type(),
                        default_expr: prop.ty.default_expr().to_owned(),
                    });
                }
            }
        }
    }

    let mut s =
        String::from("// Generated by RohKai — do not edit manually\n\nuse eframe::egui;\n\n");

    // AppState struct
    s.push_str("pub struct AppState {\n");
    for f in &fields {
        s.push_str(&format!("    pub {}: {},\n", f.name, f.ty));
    }
    s.push_str("}\n\n");

    // Default impl
    s.push_str("impl Default for AppState {\n    fn default() -> Self {\n        Self {\n");
    for f in &fields {
        s.push_str(&format!("            {}: {},\n", f.name, f.default_expr));
    }
    s.push_str("        }\n    }\n}\n\n");

    // ExportedApp
    s.push_str("pub struct ExportedApp {\n    pub state: AppState,\n}\n\n");
    s.push_str("impl Default for ExportedApp {\n    fn default() -> Self {\n        Self { state: AppState::default() }\n    }\n}\n\n");

    // Collect unique handler names
    let mut handler_names: Vec<String> = Vec::new();
    let mut seen_handlers: HashSet<String> = HashSet::new();
    for w in &tree.widgets {
        let handler = match &w.kind {
            WidgetKind::Button => resolve_export_handler_click(w),
            _ => resolve_export_handler_change(w),
        };
        if let Some(h) = handler {
            if seen_handlers.insert(h.to_owned()) {
                handler_names.push(h.to_owned());
            }
        }
    }

    // eframe::App impl
    s.push_str("impl eframe::App for ExportedApp {\n    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {\n        egui::CentralPanel::default().show(ctx, |_ui| {});\n");

    for w in &tree.widgets {
        let label = string_literal(&w.props.label);
        let label_expr = if let Some(ref lb) = w.label_binding {
            field_binding(Some(lb.as_str()))
                .map(|b| format!("&self.state.{b}"))
                .unwrap_or_else(|| label.clone())
        } else {
            label.clone()
        };
        let binding = field_binding(w.state_binding.as_deref());
        let area_id = string_literal(&format!("widget_{}", w.id));
        s.push_str(&format!(
            "        egui::Area::new(egui::Id::new({area_id}))\n            .fixed_pos(egui::pos2({:.1}, {:.1}))\n            .show(ctx, |ui| {{\n                ui.set_min_size(egui::vec2({:.1}, {:.1}));\n",
            w.rect.x, w.rect.y, w.rect.w, w.rect.h
        ));

        // enabled
        if w.enabled == Some(false) {
            s.push_str("                ui.set_enabled(false);\n");
        }

        // widget line
        let tip = w.tooltip.as_deref().map(string_literal);
        let line = match &w.kind {
            WidgetKind::Button => {
                // CITIZEN: font_size and fg_color (rich_text_expr) not applied to exported Button label.
                let rounding_chain = w
                    .corner_radius
                    .filter(|&r| r > 0.0)
                    .map(|r| format!(".rounding(egui::Rounding::same({r:.1}))"))
                    .unwrap_or_default();
                let fill_chain = w
                    .bg_color
                    .map(|c| {
                        format!(
                            ".fill(egui::Color32::from_rgb({}, {}, {}))",
                            c[0], c[1], c[2]
                        )
                    })
                    .unwrap_or_default();
                let base = format!(
                    "ui.add_sized([{:.1}, {:.1}], egui::Button::new({label_expr}){rounding_chain}{fill_chain})",
                    w.rect.w, w.rect.h
                );
                let with_tip = export_tip(base, tip.as_deref());
                if let Some(h) = resolve_export_handler_click(w) {
                    format!(
                        "                if {with_tip}.clicked() {{\n                    self.{h}();\n                }}\n"
                    )
                } else {
                    format!("                if {with_tip}.clicked() {{}}\n")
                }
            }
            WidgetKind::Label => {
                let expr = match binding {
                    Some(b) => format!("ui.label(&self.state.{b})"),
                    None => format!("ui.label({label_expr})"),
                };
                format!("                {};\n", export_tip(expr, tip.as_deref()))
            }
            WidgetKind::TextInput => match binding {
                Some(b) => {
                    let mut te = format!("egui::TextEdit::singleline(&mut self.state.{b})");
                    if !w.props.placeholder.is_empty() {
                        te.push_str(&format!(
                            ".hint_text({})",
                            string_literal(&w.props.placeholder)
                        ));
                    }
                    if w.props.password_mode {
                        te.push_str(".password(true)");
                    }
                    let base = format!("ui.add_sized([{:.1}, {:.1}], {te})", w.rect.w, w.rect.h);
                    let with_tip = export_tip(base, tip.as_deref());
                    if let Some(h) = resolve_export_handler_change(w) {
                        format!("                if {with_tip}.changed() {{\n                    self.{h}();\n                }}\n")
                    } else {
                        format!("                {with_tip};\n")
                    }
                }
                None => format!("                // TextInput {label}: set a valid Binding\n"),
            },
            WidgetKind::Slider => match binding {
                Some(b) => {
                    let mut slider = format!(
                        "egui::Slider::new(&mut self.state.{b}, {:.1}..={:.1}).text({label})",
                        w.props.min, w.props.max
                    );
                    if let Some(step) = w.props.step {
                        slider.push_str(&format!(".step_by({step} as f64)"));
                    }
                    if !w.props.show_value {
                        slider.push_str(".show_value(false)");
                    }
                    if w.props.orientation == crate::project::schema::Orientation::Vertical {
                        slider.push_str(".vertical()");
                    }
                    let base =
                        format!("ui.add_sized([{:.1}, {:.1}], {slider})", w.rect.w, w.rect.h);
                    let with_tip = export_tip(base, tip.as_deref());
                    if let Some(h) = resolve_export_handler_change(w) {
                        format!("                if {with_tip}.changed() {{\n                    self.{h}();\n                }}\n")
                    } else {
                        format!("                {with_tip};\n")
                    }
                }
                None => format!("                // Slider {label}: set a valid Binding\n"),
            },
            WidgetKind::Checkbox => match binding {
                Some(b) => {
                    let base = format!(
                        "ui.add_sized([{:.1}, {:.1}], egui::Checkbox::new(&mut self.state.{b}, {label}))",
                        w.rect.w, w.rect.h
                    );
                    let with_tip = export_tip(base, tip.as_deref());
                    if let Some(h) = resolve_export_handler_change(w) {
                        format!("                if {with_tip}.changed() {{\n                    self.{h}();\n                }}\n")
                    } else {
                        format!("                {with_tip};\n")
                    }
                }
                None => format!("                // Checkbox {label}: set a valid Binding\n"),
            },
            WidgetKind::Frame => {
                // CITIZEN: no children rendered and no Frame styling (inner_margin, stroke, fill).
                // Full fix requires iterating w.children and placing each with ui.put() or nested Areas.
                format!("                ui.group(|ui| {{ ui.label({label}); }});\n")
            }
            WidgetKind::ComboBox => match binding {
                Some(b) => {
                    let options = combo_option_values(w);
                    let selected_expr =
                        combo_selected_text_expr(&format!("self.state.{b}"), &options);
                    let mut code = format!(
                        "                let combo_resp = egui::ComboBox::from_label({label})\n                    .selected_text({selected_expr})\n                    .width({:.1})\n                    .show_ui(ui, |ui| {{\n",
                        w.rect.w
                    );
                    for option in options {
                        let option_lit = string_literal(&option);
                        code.push_str(&format!(
                            "                        ui.selectable_value(&mut self.state.{b}, {option_lit}.to_owned(), {option_lit});\n"
                        ));
                    }
                    code.push_str("                    });\n");
                    let combo_handler = resolve_export_handler_change(w);
                    let uses_response = tip.is_some() || combo_handler.is_some();
                    if uses_response {
                        code.push_str(
                            "                let combo_response = combo_resp.response;\n",
                        );
                    }
                    if combo_handler.is_some() {
                        code.push_str(
                            "                let combo_changed = combo_response.changed();\n",
                        );
                    }
                    if let Some(tip) = tip.as_deref() {
                        code.push_str(&format!(
                            "                combo_response.on_hover_text({tip});\n"
                        ));
                    }
                    if let Some(h) = combo_handler {
                        code.push_str(&format!(
                            "                if combo_changed {{\n                    self.{h}();\n                }}\n"
                        ));
                    } else if !uses_response {
                        code.push_str("                let _ = combo_resp;\n");
                    }
                    code
                }
                None => format!("                // ComboBox {label}: set a valid Binding\n"),
            },
            WidgetKind::RadioButton => match binding {
                Some(b) => {
                    let value_lit = if w.props.radio_value.is_empty() {
                        label.clone()
                    } else {
                        string_literal(&w.props.radio_value)
                    };
                    let base = format!(
                        "ui.radio_value(&mut self.state.{b}, {value_lit}.to_owned(), {label})"
                    );
                    let with_tip = export_tip(base, tip.as_deref());
                    if let Some(h) = resolve_export_handler_change(w) {
                        format!(
                            "                if {with_tip}.clicked() {{\n                    self.{h}();\n                }}\n"
                        )
                    } else {
                        format!("                {with_tip};\n")
                    }
                }
                None => format!("                // RadioButton {label}: set a valid Binding\n"),
            },
            WidgetKind::ProgressBar => match binding {
                Some(b) => {
                    let mut pb = format!("egui::ProgressBar::new(self.state.{b})");
                    if w.props.show_percentage {
                        pb.push_str(".show_percentage()");
                    }
                    if w.props.animated {
                        pb.push_str(".animate(true)");
                    }
                    let sized = format!("ui.add_sized([{:.1}, {:.1}], {pb})", w.rect.w, w.rect.h);
                    let with_tip = export_tip(sized, tip.as_deref());
                    format!("                {with_tip};\n")
                }
                None => format!("                // ProgressBar {label}: set a valid Binding\n"),
            },
        };
        s.push_str(&line);
        s.push_str("            });\n");
    }
    s.push_str("    }\n}\n");

    // Event handler stubs
    if !handler_names.is_empty() {
        s.push_str("\nimpl ExportedApp {\n");
        for h in &handler_names {
            s.push_str(&format!(
                "    fn {h}(&mut self) {{\n        // TODO: implement {h}\n    }}\n"
            ));
        }
        s.push_str("}\n");
    }

    s
}

/// Chain `.on_hover_text(tip)` in export context.
fn export_tip(expr: String, tip: Option<&str>) -> String {
    match tip {
        Some(t) if !t.is_empty() => format!("{expr}.on_hover_text({t})"),
        _ => expr,
    }
}

fn default_expr_for_widget(w: &crate::project::schema::WidgetInstance) -> String {
    match w.kind {
        WidgetKind::Slider => format!("{:.3}", w.props.default_value),
        WidgetKind::ComboBox => {
            string_literal(
                w.props
                    .options
                    .iter()
                    .find(|option| !option.trim().is_empty())
                    .map(|option| option.trim())
                    .unwrap_or("Option A"),
            ) + ".to_owned()"
        }
        _ => kind_table::state_info(&w.kind)
            .map(|info| info.default_expr.to_owned())
            .unwrap_or_else(|| "()".to_owned()),
    }
}

fn combo_option_values(widget: &crate::project::schema::WidgetInstance) -> Vec<String> {
    let options: Vec<String> = widget
        .props
        .options
        .iter()
        .filter_map(|option| {
            let trimmed = option.trim();
            (!trimmed.is_empty()).then(|| trimmed.to_owned())
        })
        .collect();

    if options.is_empty() {
        vec![widget.props.label.clone()]
    } else {
        options
    }
}

fn combo_selected_text_expr(state_expr: &str, options: &[String]) -> String {
    let fallback = options.first().map(String::as_str).unwrap_or("Option A");
    let fallback_lit = string_literal(fallback);
    format!("if {state_expr}.is_empty() {{ {fallback_lit} }} else {{ {state_expr}.as_str() }}")
}

fn resolve_export_handler_click(w: &crate::project::schema::WidgetInstance) -> Option<&str> {
    if !w.on_click.is_empty() {
        return Some(w.on_click.as_str());
    }
    w.event_handler.as_deref().filter(|s| !s.is_empty())
}

fn resolve_export_handler_change(w: &crate::project::schema::WidgetInstance) -> Option<&str> {
    if !w.on_change.is_empty() {
        return Some(w.on_change.as_str());
    }
    w.event_handler.as_deref().filter(|s| !s.is_empty())
}
