use crate::codegen::{
    field_collector,
    rust::{field_binding, string_literal},
};
use crate::project::{schema::WidgetKind, ui_tree::UiTree};
use std::collections::HashSet;
use std::fs;
use std::path::Path;
use uuid::Uuid;

const SVG_RASTERIZER_SOURCE: &str = include_str!("../canvas/svg_rasterizer.rs");

/// Write a complete compilable Rust project to `dest` folder.
pub fn write_project(tree: &UiTree, dest: &Path) -> Result<(), String> {
    let src_dir = dest.join("src");
    fs::create_dir_all(&src_dir).map_err(|e| format!("create dirs: {e}"))?;

    // Collect unique Cargo dependency lines from Custom widgets
    let mut extra_deps: Vec<String> = Vec::new();
    let mut seen_deps: HashSet<String> = HashSet::new();
    for w in &tree.widgets {
        for dep_line in &w.descriptor_cargo_deps {
            if seen_deps.insert(dep_line.clone()) {
                extra_deps.push(dep_line.clone());
            }
        }
    }

    fs::write(dest.join("Cargo.toml"), gen_cargo_toml(&extra_deps))
        .map_err(|e| format!("Cargo.toml: {e}"))?;
    fs::write(src_dir.join("main.rs"), gen_main_rs(tree)).map_err(|e| format!("main.rs: {e}"))?;
    fs::write(src_dir.join("app.rs"), gen_app_rs(tree)).map_err(|e| format!("app.rs: {e}"))?;
    Ok(())
}

// ---------------------------------------------------------------------------

fn gen_cargo_toml(extra_deps: &[String]) -> String {
    let mut s = r#"[package]
name = "exported_app"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui   = "0.29"
"#
    .to_owned();
    for dep in extra_deps {
        s.push_str(dep);
        s.push('\n');
    }
    s
}

fn gen_main_rs(tree: &UiTree) -> String {
    let title = string_literal(&tree.app_props.title);
    let w = tree.app_props.win_w as u32;
    let h = tree.app_props.win_h as u32;
    let resizable = tree.app_props.resizable;
    let min_chain = tree
        .app_props
        .min_size
        .map(|[mw, mh]| format!("\n            .with_min_inner_size([{mw:.0}.0, {mh:.0}.0])"))
        .unwrap_or_default();
    let max_chain = tree
        .app_props
        .max_size
        .map(|[mw, mh]| format!("\n            .with_max_inner_size([{mw:.0}.0, {mh:.0}.0])"))
        .unwrap_or_default();
    format!(
        r#"mod app;
use app::ExportedApp;

fn main() -> eframe::Result<()> {{
    let options = eframe::NativeOptions {{
        viewport: egui::ViewportBuilder::default()
            .with_title({title})
            .with_inner_size([{w}.0, {h}.0])
            .with_resizable({resizable}){min_chain}{max_chain},
        ..Default::default()
    }};
    eframe::run_native(
        {title},
        options,
        Box::new(|_cc| Ok(Box::new(ExportedApp::default()))),
    )
}}
"#
    )
}

// ---------------------------------------------------------------------------

fn gen_app_rs(tree: &UiTree) -> String {
    let has_images = tree.widgets.iter().any(|w| w.kind == WidgetKind::Image);
    let collected = field_collector::collect(tree);
    let fields = &collected.fields;

    let mut s =
        String::from("// Generated by RohKai — do not edit manually\n\nuse eframe::egui;\n");
    if has_images {
        s.push_str("use std::collections::HashMap;\n");
    }
    s.push('\n');
    // AppState struct
    s.push_str("pub struct AppState {\n");
    for f in fields {
        s.push_str(&format!("    pub {}: {},\n", f.name, f.ty));
    }
    s.push_str("}\n\n");

    // Default impl
    s.push_str("impl Default for AppState {\n    fn default() -> Self {\n        Self {\n");
    for f in fields {
        s.push_str(&format!("            {}: {},\n", f.name, f.default_expr));
    }
    s.push_str("        }\n    }\n}\n\n");

    // ExportedApp
    s.push_str("pub struct ExportedApp {\n    pub state: AppState,\n");
    if has_images {
        s.push_str("    svg_textures: HashMap<&'static str, egui::TextureHandle>,\n");
    }
    s.push_str("}\n\n");
    s.push_str("impl Default for ExportedApp {\n    fn default() -> Self {\n        Self {\n            state: AppState::default(),\n");
    if has_images {
        s.push_str("            svg_textures: HashMap::new(),\n");
    }
    s.push_str("        }\n    }\n}\n\n");

    // Collect unique handler names
    let mut handler_names: Vec<String> = Vec::new();
    let mut seen_handlers: HashSet<String> = HashSet::new();
    for w in &tree.widgets {
        let handler = match &w.kind {
            WidgetKind::Button => resolve_export_handler_click(w),
            _ => resolve_export_handler_change(w),
        };
        if let Some(h) = handler {
            if seen_handlers.insert(h.to_owned()) {
                handler_names.push(h.to_owned());
            }
        }
    }

    // eframe::App impl
    s.push_str("impl eframe::App for ExportedApp {\n    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {\n");
    s.push_str(&gen_theme_setup(&tree.app_props.theme));
    s.push_str("        egui::CentralPanel::default().show(ctx, |_ui| {});\n");

    let child_ids: HashSet<Uuid> = tree
        .widgets
        .iter()
        .flat_map(|w| w.children.iter().copied())
        .collect();

    for w in &tree.widgets {
        if child_ids.contains(&w.id) {
            continue;
        }
        let label = string_literal(&w.props.label);
        let label_expr = if let Some(ref lb) = w.label_binding {
            field_binding(Some(lb.as_str()))
                .map(|b| format!("&self.state.{b}"))
                .unwrap_or_else(|| label.clone())
        } else {
            label.clone()
        };
        let binding = field_binding(w.state_binding.as_deref());
        let area_id = string_literal(&format!("widget_{}", w.id));
        s.push_str(&format!(
            "        egui::Area::new(egui::Id::new({area_id}))\n            .fixed_pos(egui::pos2({:.1}, {:.1}))\n            .show(ctx, |ui| {{\n                ui.set_min_size(egui::vec2({:.1}, {:.1}));\n",
            w.rect.x, w.rect.y, w.rect.w, w.rect.h
        ));

        // enabled
        if w.enabled == Some(false) {
            s.push_str("                ui.set_enabled(false);\n");
        }

        // widget line
        let tip = w.tooltip.as_deref().map(string_literal);
        let line = match &w.kind {
            WidgetKind::Button => {
                let rounding_chain = w
                    .corner_radius
                    .filter(|&r| r > 0.0)
                    .map(|r| format!(".rounding(egui::Rounding::same({r:.1}))"))
                    .unwrap_or_default();
                let fill_chain = w
                    .bg_color
                    .map(|c| {
                        format!(
                            ".fill(egui::Color32::from_rgb({}, {}, {}))",
                            c[0], c[1], c[2]
                        )
                    })
                    .unwrap_or_default();
                let btn_label = if w.label_binding.is_some() {
                    label_expr.clone()
                } else {
                    rich_text_export_expr(&label, w.font_size, w.fg_color)
                };
                let base = format!(
                    "ui.add_sized([{:.1}, {:.1}], egui::Button::new({btn_label}){rounding_chain}{fill_chain})",
                    w.rect.w, w.rect.h
                );
                let with_tip = export_tip(base, tip.as_deref());
                if let Some(h) = resolve_export_handler_click(w) {
                    format!(
                        "                if {with_tip}.clicked() {{\n                    self.{h}();\n                }}\n"
                    )
                } else {
                    format!("                if {with_tip}.clicked() {{}}\n")
                }
            }
            WidgetKind::Label => {
                let expr = match binding {
                    Some(b) => format!("ui.label(&self.state.{b})"),
                    None => {
                        let text = if w.label_binding.is_some() {
                            label_expr.clone()
                        } else {
                            rich_text_export_expr(&label, w.font_size, w.fg_color)
                        };
                        let mut lbl = format!("egui::Label::new({text})");
                        if let Some(wrap) = w.props.text_wrap {
                            if wrap {
                                lbl.push_str(".wrap()");
                            } else {
                                lbl.push_str(".extend()");
                            }
                        }
                        format!("ui.add({lbl})")
                    }
                };
                format!("                {};\n", export_tip(expr, tip.as_deref()))
            }
            WidgetKind::TextInput => match binding {
                Some(b) => {
                    let mut te = format!("egui::TextEdit::singleline(&mut self.state.{b})");
                    if !w.props.placeholder.is_empty() {
                        te.push_str(&format!(
                            ".hint_text({})",
                            string_literal(&w.props.placeholder)
                        ));
                    }
                    if w.props.password_mode {
                        te.push_str(".password(true)");
                    }
                    let base = format!("ui.add_sized([{:.1}, {:.1}], {te})", w.rect.w, w.rect.h);
                    let with_tip = export_tip(base, tip.as_deref());
                    if let Some(h) = resolve_export_handler_change(w) {
                        format!("                if {with_tip}.changed() {{\n                    self.{h}();\n                }}\n")
                    } else {
                        format!("                {with_tip};\n")
                    }
                }
                None => format!("                // TextInput {label}: set a valid Binding\n"),
            },
            WidgetKind::Slider => match binding {
                Some(b) => {
                    let mut slider = format!(
                        "egui::Slider::new(&mut self.state.{b}, {:.1}..={:.1}).text({label})",
                        w.props.min, w.props.max
                    );
                    if let Some(step) = w.props.step {
                        slider.push_str(&format!(".step_by({step} as f64)"));
                    }
                    if !w.props.show_value {
                        slider.push_str(".show_value(false)");
                    }
                    if w.props.orientation == crate::project::schema::Orientation::Vertical {
                        slider.push_str(".vertical()");
                    }
                    let base =
                        format!("ui.add_sized([{:.1}, {:.1}], {slider})", w.rect.w, w.rect.h);
                    let with_tip = export_tip(base, tip.as_deref());
                    if let Some(h) = resolve_export_handler_change(w) {
                        format!("                if {with_tip}.changed() {{\n                    self.{h}();\n                }}\n")
                    } else {
                        format!("                {with_tip};\n")
                    }
                }
                None => format!("                // Slider {label}: set a valid Binding\n"),
            },
            WidgetKind::Checkbox => match binding {
                Some(b) => {
                    let base = format!(
                        "ui.add_sized([{:.1}, {:.1}], egui::Checkbox::new(&mut self.state.{b}, {label}))",
                        w.rect.w, w.rect.h
                    );
                    let with_tip = export_tip(base, tip.as_deref());
                    if let Some(h) = resolve_export_handler_change(w) {
                        format!("                if {with_tip}.changed() {{\n                    self.{h}();\n                }}\n")
                    } else {
                        format!("                {with_tip};\n")
                    }
                }
                None => format!("                // Checkbox {label}: set a valid Binding\n"),
            },
            WidgetKind::Frame => {
                let inner_m = w.props.inner_margin;
                let stroke_w = w.props.stroke_width;
                let stroke_col = w
                    .props
                    .stroke_color
                    .map(|c| format!("egui::Color32::from_rgb({}, {}, {})", c[0], c[1], c[2]))
                    .unwrap_or_else(|| "egui::Color32::from_gray(100)".to_owned());
                let mut frame_expr = format!(
                    "egui::Frame::none()\n                    .inner_margin({inner_m:.1})\n                    .stroke(egui::Stroke::new({stroke_w:.1}, {stroke_col}))"
                );
                if let Some(c) = w.bg_color {
                    frame_expr.push_str(&format!(
                        "\n                    .fill(egui::Color32::from_rgb({}, {}, {}))",
                        c[0], c[1], c[2]
                    ));
                }
                if let Some(r) = w.corner_radius.filter(|&r| r > 0.0) {
                    frame_expr.push_str(&format!(
                        "\n                    .rounding(egui::Rounding::same({r:.1}))"
                    ));
                }
                let mut code = format!(
                    "                {frame_expr}\n                    .show(ui, |ui| {{\n                        ui.set_min_size(egui::vec2({:.1}, {:.1}));\n",
                    w.rect.w, w.rect.h
                );
                for &child_id in &w.children {
                    if let Some(child) = tree.widgets.iter().find(|cw| cw.id == child_id) {
                        let rel_x = (child.rect.x - w.rect.x).max(0.0);
                        let rel_y = (child.rect.y - w.rect.y).max(0.0);
                        let rect_expr = format!(
                            "egui::Rect::from_min_size(ui.min_rect().min + egui::vec2({rel_x:.1}, {rel_y:.1}), egui::vec2({:.1}, {:.1}))",
                            child.rect.w, child.rect.h
                        );
                        let child_label = string_literal(&child.props.label);
                        let child_binding = field_binding(child.state_binding.as_deref());
                        code.push_str(&export_child_line(
                            child,
                            &rect_expr,
                            &child_label,
                            child_binding,
                        ));
                    }
                }
                code.push_str("                    });\n");
                code
            }
            WidgetKind::ComboBox => match binding {
                Some(b) => {
                    let options = combo_option_values(w);
                    let selected_expr =
                        combo_selected_text_expr(&format!("self.state.{b}"), &options);
                    let mut code = format!(
                        "                let combo_resp = egui::ComboBox::from_label({label})\n                    .selected_text({selected_expr})\n                    .width({:.1})\n                    .show_ui(ui, |ui| {{\n",
                        w.rect.w
                    );
                    for option in options {
                        let option_lit = string_literal(&option);
                        code.push_str(&format!(
                            "                        ui.selectable_value(&mut self.state.{b}, {option_lit}.to_owned(), {option_lit});\n"
                        ));
                    }
                    code.push_str("                    });\n");
                    let combo_handler = resolve_export_handler_change(w);
                    let uses_response = tip.is_some() || combo_handler.is_some();
                    if uses_response {
                        code.push_str(
                            "                let combo_response = combo_resp.response;\n",
                        );
                    }
                    if combo_handler.is_some() {
                        code.push_str(
                            "                let combo_changed = combo_response.changed();\n",
                        );
                    }
                    if let Some(tip) = tip.as_deref() {
                        code.push_str(&format!(
                            "                combo_response.on_hover_text({tip});\n"
                        ));
                    }
                    if let Some(h) = combo_handler {
                        code.push_str(&format!(
                            "                if combo_changed {{\n                    self.{h}();\n                }}\n"
                        ));
                    } else if !uses_response {
                        code.push_str("                let _ = combo_resp;\n");
                    }
                    code
                }
                None => format!("                // ComboBox {label}: set a valid Binding\n"),
            },
            WidgetKind::RadioButton => match binding {
                Some(b) => {
                    let value_lit = if w.props.radio_value.is_empty() {
                        label.clone()
                    } else {
                        string_literal(&w.props.radio_value)
                    };
                    let base = format!(
                        "ui.radio_value(&mut self.state.{b}, {value_lit}.to_owned(), {label})"
                    );
                    let with_tip = export_tip(base, tip.as_deref());
                    if let Some(h) = resolve_export_handler_change(w) {
                        format!(
                            "                if {with_tip}.clicked() {{\n                    self.{h}();\n                }}\n"
                        )
                    } else {
                        format!("                {with_tip};\n")
                    }
                }
                None => format!("                // RadioButton {label}: set a valid Binding\n"),
            },
            WidgetKind::ProgressBar => match binding {
                Some(b) => {
                    let mut pb = format!("egui::ProgressBar::new(self.state.{b})");
                    if w.props.show_percentage {
                        pb.push_str(".show_percentage()");
                    }
                    if w.props.animated {
                        pb.push_str(".animate(true)");
                    }
                    if let Some(c) = w.fg_color {
                        pb.push_str(&format!(
                            ".fill(egui::Color32::from_rgb({}, {}, {}))",
                            c[0], c[1], c[2]
                        ));
                    }
                    let sized = format!("ui.add_sized([{:.1}, {:.1}], {pb})", w.rect.w, w.rect.h);
                    let with_tip = export_tip(sized, tip.as_deref());
                    format!("                {with_tip};\n")
                }
                None => format!("                // ProgressBar {label}: set a valid Binding\n"),
            },
            WidgetKind::TextArea => match binding {
                Some(b) => {
                    let mut te = format!("egui::TextEdit::multiline(&mut self.state.{b})");
                    if !w.props.placeholder.is_empty() {
                        te.push_str(&format!(
                            ".hint_text({})",
                            string_literal(&w.props.placeholder)
                        ));
                    }
                    let sized =
                        format!("ui.add_sized([{:.1}, {:.1}], {te})", w.rect.w, w.rect.h);
                    format!("                {};\n", export_tip(sized, tip.as_deref()))
                }
                None => format!("                // TextArea {label}: set a valid Binding\n"),
            },
            WidgetKind::SpinBox => match binding {
                Some(b) => {
                    let dv = format!(
                        "egui::DragValue::new(&mut self.state.{b}).range({:.1}..={:.1})",
                        w.props.min, w.props.max
                    );
                    format!(
                        "                {};\n",
                        export_tip(format!("ui.add({dv})"), tip.as_deref())
                    )
                }
                None => format!("                // SpinBox {label}: set a valid Binding\n"),
            },
            WidgetKind::FontComboBox => match binding {
                Some(b) => format!(
                    "                egui::ComboBox::from_id_salt(\"{b}\")\n                    \
                    .selected_text(&self.state.{b})\n                    \
                    .show_ui(ui, |ui| {{\n                        \
                    for font in [\"Proportional\", \"Monospace\"] {{\n                            \
                    ui.selectable_value(&mut self.state.{b}, font.to_owned(), font);\n                        \
                    }}\n                    }});\n"
                ),
                None => {
                    format!("                // FontComboBox {label}: set a valid Binding\n")
                }
            },
            WidgetKind::HorizontalSpacer => {
                format!("                ui.add_space({:.1});\n", w.rect.w)
            }
            WidgetKind::VerticalSpacer => {
                format!("                ui.add_space({:.1});\n", w.rect.h)
            }
            WidgetKind::GroupBox => {
                let lbl = string_literal(&w.props.label);
                format!(
                    "                egui::Frame::group(ui.style()).show(ui, |ui| {{\n                    ui.label({lbl});\n                }});\n"
                )
            }
            WidgetKind::VLayout => {
                "                ui.vertical(|_ui| {});\n".to_string()
            }
            WidgetKind::HLayout => {
                "                ui.horizontal(|_ui| {});\n".to_string()
            }
            WidgetKind::ScrollArea => {
                "                egui::ScrollArea::vertical().show(ui, |_ui| {});\n".to_string()
            }
            WidgetKind::Image => image_export_line(w, tip.as_deref(), 16),
            WidgetKind::Custom(_) => {
                if let Some(ref tpl) = w.descriptor_export_tpl {
                    let rendered = crate::codegen::widget_descriptor::apply_template(
                        tpl,
                        w,
                        w.descriptor_name.as_deref().unwrap_or("Custom"),
                    );
                    format!("                {rendered}\n")
                } else {
                    format!(
                        "                // Custom widget {:?}: descriptor not loaded\n",
                        w.kind
                    )
                }
            }
        };
        s.push_str(&line);
        s.push_str("            });\n");
    }
    s.push_str("    }\n}\n");

    // Event handler stubs and Image helpers
    if !handler_names.is_empty() || has_images {
        s.push_str("\nimpl ExportedApp {\n");
        for h in &handler_names {
            s.push_str(&format!(
                "    fn {h}(&mut self) {{\n        // TODO: implement {h}\n    }}\n"
            ));
        }
        if has_images {
            s.push_str(
                "    fn show_svg_image(\n        &mut self,\n        ui: &mut egui::Ui,\n        ctx: &egui::Context,\n        key: &'static str,\n        svg_source: &'static str,\n        size: egui::Vec2,\n    ) -> egui::Response {\n        let size = egui::vec2(size.x.max(1.0), size.y.max(1.0));\n        let tex = self.svg_textures.entry(key).or_insert_with(|| {\n            let image = rohkai_svg::rasterize(svg_source, size.x.ceil() as u32, size.y.ceil() as u32);\n            ctx.load_texture(key, image, egui::TextureOptions::LINEAR)\n        });\n        ui.add(egui::Image::new((tex.id(), size)))\n    }\n",
            );
        }
        s.push_str("}\n");
    }

    if has_images {
        s.push_str("\n#[allow(dead_code)]\nmod rohkai_svg {\n");
        s.push_str(SVG_RASTERIZER_SOURCE);
        if !SVG_RASTERIZER_SOURCE.ends_with('\n') {
            s.push('\n');
        }
        s.push_str("}\n");
    }

    s
}

/// Chain `.on_hover_text(tip)` in export context.
fn export_tip(expr: String, tip: Option<&str>) -> String {
    match tip {
        Some(t) if !t.is_empty() => format!("{expr}.on_hover_text({t})"),
        _ => expr,
    }
}

fn combo_option_values(widget: &crate::project::schema::WidgetInstance) -> Vec<String> {
    let options: Vec<String> = widget
        .props
        .options
        .iter()
        .filter_map(|option| {
            let trimmed = option.trim();
            (!trimmed.is_empty()).then(|| trimmed.to_owned())
        })
        .collect();

    if options.is_empty() {
        vec![widget.props.label.clone()]
    } else {
        options
    }
}

fn combo_selected_text_expr(state_expr: &str, options: &[String]) -> String {
    let fallback = options.first().map(String::as_str).unwrap_or("Option A");
    let fallback_lit = string_literal(fallback);
    format!("if {state_expr}.is_empty() {{ {fallback_lit} }} else {{ {state_expr}.as_str() }}")
}

fn resolve_export_handler_click(w: &crate::project::schema::WidgetInstance) -> Option<&str> {
    if !w.on_click.is_empty() {
        return Some(w.on_click.as_str());
    }
    w.event_handler.as_deref().filter(|s| !s.is_empty())
}

fn resolve_export_handler_change(w: &crate::project::schema::WidgetInstance) -> Option<&str> {
    if !w.on_change.is_empty() {
        return Some(w.on_change.as_str());
    }
    w.event_handler.as_deref().filter(|s| !s.is_empty())
}

fn rich_text_export_expr(
    label_lit: &str,
    font_size: Option<f32>,
    fg_color: Option<[u8; 3]>,
) -> String {
    let color = fg_color.map(|c| format!("egui::Color32::from_rgb({}, {}, {})", c[0], c[1], c[2]));
    match (font_size, color.as_deref()) {
        (Some(size), Some(col)) => {
            format!("egui::RichText::new({label_lit}).size({size:.1}).color({col})")
        }
        (Some(size), None) => format!("egui::RichText::new({label_lit}).size({size:.1})"),
        (None, Some(col)) => format!("egui::RichText::new({label_lit}).color({col})"),
        (None, None) => label_lit.to_owned(),
    }
}

fn export_child_line(
    child: &crate::project::schema::WidgetInstance,
    rect_expr: &str,
    child_label: &str,
    child_binding: Option<&str>,
) -> String {
    match &child.kind {
        WidgetKind::Button => format!(
            "                        if ui.put({rect_expr}, egui::Button::new({child_label})).clicked() {{}}\n"
        ),
        WidgetKind::Label => match child_binding {
            Some(b) => format!("                        ui.put({rect_expr}, egui::Label::new(&self.state.{b}));\n"),
            None => format!("                        ui.put({rect_expr}, egui::Label::new({child_label}));\n"),
        },
        WidgetKind::TextInput => match child_binding {
            Some(b) => format!(
                "                        ui.put({rect_expr}, egui::TextEdit::singleline(&mut self.state.{b}));\n"
            ),
            None => format!("                        // TextInput {child_label}: set a valid Binding\n"),
        },
        WidgetKind::Slider => match child_binding {
            Some(b) => format!(
                "                        ui.put({rect_expr}, egui::Slider::new(&mut self.state.{b}, {:.1}..={:.1}).text({child_label}));\n",
                child.props.min, child.props.max
            ),
            None => format!("                        // Slider {child_label}: set a valid Binding\n"),
        },
        WidgetKind::Checkbox => match child_binding {
            Some(b) => format!(
                "                        ui.put({rect_expr}, egui::Checkbox::new(&mut self.state.{b}, {child_label}));\n"
            ),
            None => format!("                        // Checkbox {child_label}: set a valid Binding\n"),
        },
        WidgetKind::ComboBox => match child_binding {
            Some(b) => format!(
                "                        ui.put({rect_expr}, egui::Label::new(self.state.{b}.as_str())); // ComboBox\n"
            ),
            None => format!("                        // ComboBox {child_label}: set a valid Binding\n"),
        },
        WidgetKind::RadioButton => match child_binding {
            Some(b) => {
                let value_lit = if child.props.radio_value.is_empty() {
                    child_label.to_owned()
                } else {
                    string_literal(&child.props.radio_value)
                };
                format!(
                    "                        ui.radio_value(&mut self.state.{b}, {value_lit}.to_owned(), {child_label});\n"
                )
            }
            None => format!("                        // RadioButton {child_label}: set a valid Binding\n"),
        },
        WidgetKind::ProgressBar => match child_binding {
            Some(b) => {
                let mut pb = format!("egui::ProgressBar::new(self.state.{b})");
                if child.props.show_percentage {
                    pb.push_str(".show_percentage()");
                }
                if child.props.animated {
                    pb.push_str(".animate(true)");
                }
                format!("                        ui.put({rect_expr}, {pb});\n")
            }
            None => format!("                        // ProgressBar {child_label}: set a valid Binding\n"),
        },
        WidgetKind::Frame
        | WidgetKind::GroupBox
        | WidgetKind::VLayout
        | WidgetKind::HLayout
        | WidgetKind::ScrollArea => format!(
            "                        // Nested container {:?} - not recursive in export\n",
            child.kind
        ),
        WidgetKind::TextArea => match child_binding {
            Some(b) => format!(
                "                        ui.put({rect_expr}, egui::TextEdit::multiline(&mut self.state.{b}));\n"
            ),
            None => format!("                        // TextArea {child_label}: set a valid Binding\n"),
        },
        WidgetKind::SpinBox => match child_binding {
            Some(b) => format!(
                "                        ui.put({rect_expr}, egui::DragValue::new(&mut self.state.{b}).range({:.1}..={:.1}));\n",
                child.props.min, child.props.max
            ),
            None => format!("                        // SpinBox {child_label}: set a valid Binding\n"),
        },
        WidgetKind::FontComboBox => match child_binding {
            Some(b) => format!(
                "                        ui.put({rect_expr}, egui::Label::new(self.state.{b}.as_str())); // FontComboBox\n"
            ),
            None => format!("                        // FontComboBox {child_label}: set a valid Binding\n"),
        },
        WidgetKind::HorizontalSpacer => {
            format!("                        ui.add_space({:.1}); // HorizontalSpacer\n", child.rect.w)
        }
        WidgetKind::VerticalSpacer => {
            format!("                        ui.add_space({:.1}); // VerticalSpacer\n", child.rect.h)
        }
        WidgetKind::Image => image_export_child_line(child, rect_expr),
        WidgetKind::Custom(_) => {
            if let Some(ref tpl) = child.descriptor_export_tpl {
                let rendered = crate::codegen::widget_descriptor::apply_template(
                    tpl,
                    child,
                    child.descriptor_name.as_deref().unwrap_or("Custom"),
                );
                format!("                        {rendered}\n")
            } else {
                format!(
                    "                        // Custom child {:?}: descriptor not loaded\n",
                    child.kind
                )
            }
        }
    }
}

fn image_export_line(
    widget: &crate::project::schema::WidgetInstance,
    tip: Option<&str>,
    indent: usize,
) -> String {
    let pad = " ".repeat(indent);
    let key = string_literal(&format!("svg_{}", widget.id));
    let svg_source = raw_string_literal(widget.svg_source.as_deref().unwrap_or(""));
    let base = format!(
        "self.show_svg_image(ui, ctx, {key}, {svg_source}, egui::vec2({:.1}, {:.1}))",
        widget.rect.w, widget.rect.h
    );
    let expr = export_tip(base, tip);
    format!("{pad}{expr};\n")
}

fn image_export_child_line(
    child: &crate::project::schema::WidgetInstance,
    rect_expr: &str,
) -> String {
    let key = string_literal(&format!("svg_{}", child.id));
    let svg_source = raw_string_literal(child.svg_source.as_deref().unwrap_or(""));
    format!(
        "                        ui.allocate_ui_at_rect({rect_expr}, |ui| {{\n                            self.show_svg_image(ui, ctx, {key}, {svg_source}, {rect_expr}.size());\n                        }});\n"
    )
}

fn gen_theme_setup(theme: &crate::project::schema::ThemeSettings) -> String {
    let mode = if theme.dark_mode {
        "egui::Visuals::dark()"
    } else {
        "egui::Visuals::light()"
    };
    let [r, g, b] = theme.accent_color;
    let is_default_accent = (r, g, b) == (52, 211, 153);
    let rounding_code = theme
        .global_corner_radius
        .map(|cr| {
            format!(
                "        let r = egui::Rounding::same({cr:.1});\n\
                 visuals.widgets.noninteractive.rounding = r;\n\
                 visuals.widgets.inactive.rounding = r;\n\
                 visuals.widgets.hovered.rounding = r;\n\
                 visuals.widgets.active.rounding = r;\n\
                 visuals.widgets.open.rounding = r;\n"
            )
        })
        .unwrap_or_default();
    let font_code = theme
        .base_font_size
        .map(|fs| {
            format!(
                "        let mut style = (*ctx.style()).clone();\n\
                 for font_id in style.text_styles.values_mut() {{ font_id.size = {fs:.1}; }}\n\
                 ctx.set_style(style);\n"
            )
        })
        .unwrap_or_default();
    // Skip emitting theme code if it's the default dark mode with default accent
    if theme.dark_mode
        && is_default_accent
        && theme.global_corner_radius.is_none()
        && font_code.is_empty()
    {
        return String::new();
    }
    format!(
        "        let mut visuals = {mode};\n\
         visuals.hyperlink_color = egui::Color32::from_rgb({r}, {g}, {b});\n\
         visuals.selection.bg_fill = egui::Color32::from_rgba_premultiplied({r}, {g}, {b}, 90);\n\
         {rounding_code}\
         ctx.set_visuals(visuals);\n\
         {font_code}"
    )
}

fn raw_string_literal(value: &str) -> String {
    let mut hashes = 0usize;
    loop {
        let fence = format!("\"{}", "#".repeat(hashes));
        if !value.contains(&fence) {
            return format!("r{}\"{}\"{}", "#".repeat(hashes), value, "#".repeat(hashes));
        }
        hashes += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::project::schema::{Rect, WidgetInstance};

    #[test]
    fn image_widget_export_embeds_svg_renderer() {
        let tree = UiTree {
            widgets: vec![WidgetInstance {
                id: Uuid::nil(),
                kind: WidgetKind::Image,
                rect: Rect {
                    x: 10.0,
                    y: 20.0,
                    w: 120.0,
                    h: 80.0,
                },
                svg_source: Some("<svg/>".to_owned()),
                ..Default::default()
            }],
            ..Default::default()
        };

        let generated = gen_app_rs(&tree);

        assert!(generated.contains("mod rohkai_svg"));
        assert!(generated.contains("fn show_svg_image"));
        assert!(generated.contains("use std::collections::HashMap;"));
        assert!(generated.contains("svg_textures: HashMap"));
        assert!(generated.contains("rohkai_svg::rasterize"));
        assert!(generated.contains("ui.add(egui::Image::new((tex.id(), size)))"));
        assert!(generated.contains("pub fn rasterize"));
        assert!(generated.contains("r\"<svg/>\""));
        assert!(!generated.contains("egui::Frame::none()"));
        assert!(!generated.contains("image_export_frame_placeholder_line"));
    }
}
