use crate::codegen::rust::{field_binding, string_literal};
use crate::project::{schema::WidgetKind, ui_tree::UiTree};
use std::collections::HashSet;
use std::fs;
use std::path::Path;

/// Write a complete compilable Rust project to `dest` folder.
pub fn write_project(tree: &UiTree, dest: &Path) -> Result<(), String> {
    let src_dir = dest.join("src");
    fs::create_dir_all(&src_dir).map_err(|e| format!("create dirs: {e}"))?;
    fs::write(dest.join("Cargo.toml"), gen_cargo_toml()).map_err(|e| format!("Cargo.toml: {e}"))?;
    fs::write(src_dir.join("main.rs"), gen_main_rs(tree)).map_err(|e| format!("main.rs: {e}"))?;
    fs::write(src_dir.join("app.rs"), gen_app_rs(tree)).map_err(|e| format!("app.rs: {e}"))?;
    Ok(())
}

// ---------------------------------------------------------------------------

fn gen_cargo_toml() -> String {
    r#"[package]
name = "exported_app"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui   = "0.29"
"#
    .to_owned()
}

fn gen_main_rs(tree: &UiTree) -> String {
    let title = string_literal(&tree.app_props.title);
    let w = tree.app_props.win_w as u32;
    let h = tree.app_props.win_h as u32;
    format!(
        r#"mod app;
use app::ExportedApp;

fn main() -> eframe::Result<()> {{
    let options = eframe::NativeOptions {{
        viewport: egui::ViewportBuilder::default()
            .with_title({title})
            .with_inner_size([{w}.0, {h}.0]),
        ..Default::default()
    }};
    eframe::run_native(
        {title},
        options,
        Box::new(|_cc| Ok(Box::new(ExportedApp::default()))),
    )
}}
"#
    )
}

// ---------------------------------------------------------------------------

struct BoundField {
    name: String,
    ty: &'static str,
    default_expr: &'static str,
}

fn gen_app_rs(tree: &UiTree) -> String {
    let mut seen: HashSet<String> = HashSet::new();
    let fields: Vec<BoundField> = tree
        .widgets
        .iter()
        .filter_map(|w| {
            let name = field_binding(w.state_binding.as_deref())?.to_owned();
            if !seen.insert(name.clone()) {
                return None;
            }
            let (ty, default_expr) = match &w.kind {
                WidgetKind::Button | WidgetKind::Frame => return None,
                WidgetKind::Label
                | WidgetKind::TextInput
                | WidgetKind::ComboBox
                | WidgetKind::RadioButton => ("String", "String::new()"),
                WidgetKind::Slider | WidgetKind::ProgressBar => ("f32", "0.0"),
                WidgetKind::Checkbox => ("bool", "false"),
            };
            Some(BoundField {
                name,
                ty,
                default_expr,
            })
        })
        .collect();

    let mut s =
        String::from("// Generated by RohKai — do not edit manually\n\nuse eframe::egui;\n\n");

    // AppState struct
    s.push_str("pub struct AppState {\n");
    for f in &fields {
        s.push_str(&format!("    pub {}: {},\n", f.name, f.ty));
    }
    s.push_str("}\n\n");

    // Default impl
    s.push_str("impl Default for AppState {\n    fn default() -> Self {\n        Self {\n");
    for f in &fields {
        s.push_str(&format!("            {}: {},\n", f.name, f.default_expr));
    }
    s.push_str("        }\n    }\n}\n\n");

    // ExportedApp
    s.push_str("pub struct ExportedApp {\n    pub state: AppState,\n}\n\n");
    s.push_str("impl Default for ExportedApp {\n    fn default() -> Self {\n        Self { state: AppState::default() }\n    }\n}\n\n");

    // eframe::App impl
    s.push_str("impl eframe::App for ExportedApp {\n    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {\n        egui::CentralPanel::default().show(ctx, |_ui| {});\n");

    for w in &tree.widgets {
        let label = string_literal(&w.props.label);
        let binding = field_binding(w.state_binding.as_deref());
        let area_id = string_literal(&format!("widget_{}", w.id));
        s.push_str(&format!(
            "        egui::Area::new(egui::Id::new({area_id}))\n            .fixed_pos(egui::pos2({:.1}, {:.1}))\n            .show(ctx, |ui| {{\n                ui.set_min_size(egui::vec2({:.1}, {:.1}));\n",
            w.rect.x, w.rect.y, w.rect.w, w.rect.h
        ));
        let line = match &w.kind {
            WidgetKind::Button => {
                format!(
                    "                if ui.add_sized([{:.1}, {:.1}], egui::Button::new({label})).clicked() {{}}\n",
                    w.rect.w, w.rect.h
                )
            }
            WidgetKind::Label => match binding {
                Some(b) => format!("                ui.label(&self.state.{b});\n"),
                None    => format!("                ui.label({label});\n"),
            },
            WidgetKind::TextInput => match binding {
                Some(b) => format!(
                    "                ui.add_sized([{:.1}, {:.1}], egui::TextEdit::singleline(&mut self.state.{b}));\n",
                    w.rect.w, w.rect.h
                ),
                None    => format!("                // TextInput {label}: set a valid Binding\n"),
            },
            WidgetKind::Slider => match binding {
                Some(b) => format!(
                    "                ui.add_sized([{:.1}, {:.1}], egui::Slider::new(&mut self.state.{b}, {:.1}..={:.1}).text({label}));\n",
                    w.rect.w, w.rect.h, w.props.min, w.props.max
                ),
                None => format!("                // Slider {label}: set a valid Binding\n"),
            },
            WidgetKind::Checkbox => match binding {
                Some(b) => format!(
                    "                ui.add_sized([{:.1}, {:.1}], egui::Checkbox::new(&mut self.state.{b}, {label}));\n",
                    w.rect.w, w.rect.h
                ),
                None    => format!("                // Checkbox {label}: set a valid Binding\n"),
            },
            WidgetKind::Frame => {
                format!("                ui.group(|ui| {{ ui.label({label}); }});\n")
            }
            WidgetKind::ComboBox => match binding {
                Some(b) => format!(
                    "                egui::ComboBox::from_label({label}).selected_text(self.state.{b}.as_str()).width({:.1}).show_ui(ui, |_ui| {{}});\n",
                    w.rect.w
                ),
                None => format!("                // ComboBox {label}: set a valid Binding\n"),
            },
            WidgetKind::RadioButton => match binding {
                Some(b) => format!(
                    "                ui.radio_value(&mut self.state.{b}, {label}.to_owned(), {label});\n"
                ),
                None => format!("                // RadioButton {label}: set a valid Binding\n"),
            },
            WidgetKind::ProgressBar => match binding {
                Some(b) => format!(
                    "                ui.add_sized([{:.1}, {:.1}], egui::ProgressBar::new(self.state.{b}).text({label}));\n",
                    w.rect.w, w.rect.h
                ),
                None => format!("                // ProgressBar {label}: set a valid Binding\n"),
            },
        };
        s.push_str(&line);
        s.push_str("            });\n");
    }

    s.push_str("    }\n}\n");
    s
}
