use crate::codegen::field_collector;
use crate::project::schema::DbBinding;
use crate::project::ui_tree::UiTree;

/// Walk the UiTree and emit an AppState struct with the required fields.
pub fn emit(tree: &UiTree) -> String {
    let collected = field_collector::collect(tree);

    // Design-time component state fields (DataSource etc.)
    let component_pairs =
        crate::codegen::component_state::component_state_field_pairs(&tree.app_props.components);

    // Stage 13 — collect widgets that have a DB binding.
    let db_bindings: Vec<(String, &DbBinding)> = tree
        .widgets
        .iter()
        .filter_map(|w| {
            w.db_binding.as_ref().map(|b| {
                // Use the state_binding as the field name if present, else the widget id.
                let field_name = w
                    .state_binding
                    .as_deref()
                    .filter(|s| !s.is_empty())
                    .map(|s| s.to_owned())
                    .unwrap_or_else(|| format!("widget_{}", &w.id.to_string().replace('-', "_")));
                (field_name, b)
            })
        })
        .collect();

    let has_db = !db_bindings.is_empty();

    let mut out = String::from("// Generated AppState - do not edit manually\nstruct AppState {\n");
    for f in &collected.fields {
        out.push_str(&format!("    {}: {},\n", f.name, f.ty));
    }
    for (decl, _) in &component_pairs {
        out.push_str(decl);
        out.push('\n');
    }
    // Emit a single db_conn field when any widget has a DB binding.
    if has_db {
        out.push_str(
            "    // Stage 13 — DB connection (None until load_from_db() is called)\n",
        );
        out.push_str("    db_conn: Option<rusqlite::Connection>,\n");
    }
    for w in &collected.warnings {
        out.push_str("    // ");
        out.push_str(w);
        out.push('\n');
    }
    out.push_str("}\n\n");
    out.push_str("impl Default for AppState {\n    fn default() -> Self {\n        Self {\n");
    for f in &collected.fields {
        out.push_str(&format!("            {}: {},\n", f.name, f.default_expr));
    }
    for (_, default_line) in &component_pairs {
        out.push_str(default_line);
        out.push('\n');
    }
    if has_db {
        out.push_str("            db_conn: None,\n");
    }
    out.push_str("        }\n    }\n}\n");

    // Emit load_from_db method stub when at least one binding is present.
    if has_db {
        out.push_str(emit_load_from_db(&db_bindings).as_str());
    }

    out
}

/// Emit an `impl AppState { fn load_from_db(&mut self, path: &str) { … } }`
/// stub with one SELECT per DB-bound widget.
///
/// **Invariant 10**: All SQL values are passed via `rusqlite::params![]`.
/// No SQL string is assembled with `format!()` inside the generated code.
fn emit_load_from_db(bindings: &[(String, &DbBinding)]) -> String {
    let mut out = String::new();
    out.push_str("\nimpl AppState {\n");
    out.push_str("    /// Load widget values from the database at `path`.\n");
    out.push_str("    /// Generated by RohKai Stage 13 — edit as needed.\n");
    out.push_str("    fn load_from_db(&mut self, path: &str) -> Result<(), rusqlite::Error> {\n");
    out.push_str("        let conn = rusqlite::Connection::open(path)?;\n");

    for (field_name, binding) in bindings {
        // Validate the table/column names are safe ASCII identifiers before
        // interpolating them.  This mirrors SqliteEngine::validate_identifier.
        let table = sanitise_ident(&binding.table);
        let column = sanitise_ident(&binding.column);
        // SELECT with LIMIT 1; the limit is a bound param (Invariant 10).
        out.push('\n');
        out.push_str(&format!(
            "        // DB binding: {table}.{column} -> self.{field_name}\n"
        ));
        out.push_str("        {\n");
        out.push_str(&format!(
            "            let mut stmt = conn.prepare(\"SELECT {column} FROM {table} LIMIT ?1\")?;\n"
        ));
        out.push_str(
            "            if let Ok(val) = stmt.query_row(rusqlite::params![1i64], |row| row.get(0)) {\n"
        );
        out.push_str(&format!("                self.{field_name} = val;\n"));
        out.push_str("            }\n");
        out.push_str("        }\n");
    }

    out.push('\n');
    out.push_str("        self.db_conn = Some(conn);\n");
    out.push_str("        Ok(())\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

/// Replace any character that is not ASCII alphanumeric or `_` with `_`.
/// This is the codegen-side mirror of `SqliteEngine::validate_identifier`.
fn sanitise_ident(s: &str) -> String {
    if s.is_empty() {
        return "unknown".to_owned();
    }
    s.chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}
